---
language: python
cache: pip
env:
  global:
    - MAKEFLAGS="-j 2"
jobs:
  include:
    - name: "Python 3.7 Linux"
      python: 3.7
    - name: "Python 3.8 Linux"
      python: 3.8
    - name: "Python 3.7 macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
install:
  - pip3 install --upgrade pip
  - pip install .[dev]
script:
  - make lint
  - make safety
  - make unittests
  - make integration
after_success: coveralls
