---
language: python
python:
  - 3.8
  - 3.7
sudo: required
dist: xenial
cache: pip
install:
  - pip install .[dev]
env:
  global:
    - MAKEFLAGS="-j 2"
script:
  - make lint
  - make safety
  - make unittests
after_success: coveralls
