"""vater metadata."""
__name__ = "vater"
__description__ = ""
__version__ = "0.1.0"
__author__ = "myslak71"
__author_email__ = "myslak@protonmail.com"
__url__ = ""
__license__ = ""
__copyright__ = "Copyright 2019 myslak71"
__keywords__ = ["vat"]
__download_url__ = ""
