"""vater metadata module."""
__name__ = "vater"
__description__ = "Client for polish VAT payers register API"
__version__ = "0.1.2"
__author__ = "myslak71"
__author_email__ = "myslak@protonmail.com"
__url__ = "https://github.com/myslak71/vater"
__license__ = "MIT"
__copyright__ = "Copyright 2019 myslak71"
__keywords__ = "vat", "client", "api"
__download_url__ = "https://github.com/myslak71/vater/archive/v0.1.2.tar.gz"
__apiversion__ = "1.3.0"
